[Feat/#40] TodayMainQuizView에 애니메이션 추가
SJU-CapstoneDesign/D3N-iOS pull request #46
Opened 2023-10-27 00:47 UTC by greetings1012

## PR 요약

#### 📌 변경 사항

##### ✅ PR check list

#### Linked Issue

close #40

2023-10-27 04:18 UTC, mooyoung2309 commented
고생하셨습니다!!

방금 시뮬레이터로 돌려보고왔는데, 구현 방향은 좋은것 같아요! 이제 디테일을 잡아가면 될것같아요! 

제생각에 조금 더 앱스토어 같이 구현하려면 이렇게 되어야 할 것 같아요.

제가 조금 더 자세하게 앱스토어 투데이를 분석해보았는데요. 이렇습니다.

## 모든 경우의 수는 이렇습니다. 
1. 탭이 시작될때 탭한 Position이 투데이(VStack) 영역에 있으면 애니메이션을 시작합니다. (스케일 다운 애니메이션)
2. 탭을 뗄때 드래그 없이 탭만 떼었을 경우에는 이벤트를 동작합니다. (전체 뉴스 페이지로 이동)
3. 탭을 뗄때 드래그를 했었던 상태라면 이벤트 동작을 무시합니다. (아무일이 없음)
4. 드래그를 한다면 애니메이션을 되돌립니다. (스케일 업 애니메이션)

2023-10-31 02:31 UTC, mooyoung2309 requested changes
고생하셨습니다..!!! 똑같아요 실제랑 근데 config파일이 깃에 올라와있네요.. 이부분을 깃에 올리면 안되니깐 .gitignore에 해당 부분을 추가해서 깃에 안올라오게 해주세요!

2023-10-31 02:31 UTC, mooyoung2309 commented on Targets/D3N/Sources/Feature/Today/Main/TodayMainView.swift
> +            )
이부분을 이렇게 변경해도 좋을것같아요! 찾아보니깐 파라미터 이름이 변경되어있었어요. 그리고 pressing이 true일때와 false일때 모두 동작이 된다면 if 문을 없애고 항상 동작되도록 해도 좋을것 같습니다. 아래는 고친 코드입니다.

```swift
            .onLongPressGesture(
                minimumDuration: .infinity,
                perform: {
                    //TODO: 꾹 눌렀을 때 동작 추가
                }
            ) { pressing in
                withAnimation(.easeOut(duration: 0.3)){
                    isPressing = pressing
                }
            }
```

2023-10-31 09:08 UTC, greetings1012 commented on Targets/D3N/Sources/Feature/Today/Main/TodayMainView.swift
> +            )
이게 훨씬 깔끔하네요! 변경해서 merge하겠습니다.

2023-10-31 09:09 UTC, merged